# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/maguro/extract-files.sh - DO NOT EDIT

ifeq ($(TARGET_DEVICE),maguro)
LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := LMprec_508
LOCAL_MODULE_OWNER := Eclipse
LOCAL_SRC_FILES := LMprec_508.emd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .emd
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/media
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := PFFprec_600
LOCAL_MODULE_OWNER := Eclipse
LOCAL_SRC_FILES := PFFprec_600.emd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .emd
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/media
include $(BUILD_PREBUILT)

endif

